# Nonlinear steady momentum balance in the same solenoidal basis as the Stokes
# solve. -(U·∇)U = U×curl(U) - ∇(|U|²/2); the last term is absorbed in pressure.

"""Evaluate the physical vorticity of native mean-flow potentials."""
function _mean_vorticity_grid(flow::SolenoidalMeanFlow{T},i,g) where T
    R=Dict{Tuple{Int,Int},T}(); S=empty(R); V=empty(R); r=flow.r[i]
    for (key,p) in flow.p
        l,m=key; q=l*(l+1)
        R[key]=-q*flow.t[key][i]/r^2
        S[key]=-flow.dt[key][i]/r
        V[key]=(flow.d2p[key][i]-q*p[i]/r^2)/r
    end
    wr=sh_synthesize(R,g)
    wθ=sh_synthesize(S,g;Yf=_sh_dYθ)-sh_synthesize(V,g;Yf=_sh_dYφ_over_sin)
    wφ=sh_synthesize(S,g;Yf=_sh_dYφ_over_sin)+sh_synthesize(V,g;Yf=_sh_dYθ)
    wr,wθ,wφ
end

"""Project U×curl(U), including all retained harmonics generated by products."""
function _mean_inertia(flow::SolenoidalMeanFlow{T},D1) where T
    g=sh_grid(flow.lmax,flow.mmax,T); N=length(flow.r)
    modes=[(l,m) for m in -g.mmax:g.mmax for l in max(1,abs(m)):g.lmax]
    R=Dict(k=>zeros(T,N) for k in modes)
    S=Dict(k=>zeros(T,N) for k in modes)
    V=Dict(k=>zeros(T,N) for k in modes)
    for i in 1:N
        ur,uθ,uφ=_mean_flow_grid(flow,i,g)
        wr,wθ,wφ=_mean_vorticity_grid(flow,i,g)
        fr=uθ.*wφ-uφ.*wθ
        fθ=uφ.*wr-ur.*wφ
        fφ=ur.*wθ-uθ.*wr
        radial=sh_analyze(fr,g)
        spheroidal=sh_horizontal_divergence(fθ,fφ,g)
        toroidal=sh_horizontal_divergence(fφ,-fθ,g)
        for k in modes
            q=k[1]*(k[1]+1)
            R[k][i]=radial[k]
            S[k][i]=-spheroidal[k]/q
            V[k][i]=-toroidal[k]/q
        end
    end
    # Eliminate the pressure by R - ∂r(r S). Angular products are dealiased by
    # the oversampled SH grid; radial derivatives use the collocation operator.
    p=Dict(k=>R[k]-D1*(flow.r.*S[k]) for k in modes)
    (p=p,t=V,radial=R,spheroidal=S)
end

function _blend_mean_flow(a::SolenoidalMeanFlow{T},b::SolenoidalMeanFlow{T},α,D,D2) where T
    ks=union(keys(a.p),keys(b.p)); N=length(a.r)
    blend(da,db)=Dict(k=>(1-α).*get(da,k,zeros(T,N)) .+ α.*get(db,k,zeros(T,N)) for k in ks)
    p=blend(a.p,b.p); t=blend(a.t,b.t)
    SolenoidalMeanFlow(a.lmax,a.mmax,a.r,p,t,Dict(k=>D*v for (k,v) in p),
        Dict(k=>D2*v for (k,v) in p),Dict(k=>D*v for (k,v) in t))
end

"""Momentum collocation defect relative to the size of the equation's terms, and the
mechanical boundary/gauge defect of the row-scaled system relative to the largest
potential.

A diagnostic, not a convergence measure: through the viscous D⁴ rows even an exact
linear solve leaves a defect that grows roughly like N⁹."""
function _mean_momentum_residual(theta,flow,D,D2,E,Ra,Pr,mechanical_bc,inertia,systems)
    r=flow.r; T=eltype(r); N=length(r)
    θ=_sh_rescale(theta,+1); β=T(Ra*E^2/(Pr*(last(r)-first(r))^3))
    residual=zero(T); boundary=zero(T); terms=zero(T); xscale=zero(T)
    for am in 0:flow.mmax
        active=any(l>0 && abs(m)==am && any(!iszero,v) for ((l,m),v) in θ) ||
            any(abs(m)==am for (l,m) in keys(flow.p))
        if inertia!==nothing
            active |= any(abs(m)==am && any(!iszero,v) for d in (inertia.p,inertia.t) for ((l,m),v) in d)
        end
        active || continue
        system=get!(systems,am) do
            _mean_momentum_system(r,D,D2,E,flow.lmax,am,mechanical_bc)
        end
        f=_mean_momentum_rhs(system,θ,inertia,r,β)
        x=zeros(T,length(f)); n=length(system.modes)
        for (a,k) in enumerate(system.modes)
            rows=(a-1)*N+1:a*N
            x[rows]=get(flow.p,k,zeros(T,N)); x[n*N .+ rows]=get(flow.t,k,zeros(T,N))
        end
        # A stress-free gauge multiplier is not a physical applied torque. Keep
        # it zero here so nonzero torque cannot be hidden in the residual.
        Ax=system.matrix*x; defect=Ax-f
        physical=system.physical; constraints=setdiff(eachindex(f),physical)
        residual=max(residual,maximum(abs,defect[physical]))
        terms=max(terms,maximum(abs,Ax[physical]),maximum(abs,f[physical]))
        boundary=max(boundary,maximum(abs,defect[constraints]./system.scales[constraints]))
        xscale=max(xscale,maximum(abs,x))
    end
    (iszero(terms) ? residual : residual/terms),(iszero(xscale) ? boundary : boundary/xscale)
end

"""Thermal boundary-condition defect relative to the largest orthonormal temperature
coefficient. Flux rows are divided by the largest derivative weight at the wall."""
function _mean_thermal_boundary_residual(theta,D,bc)
    T=eltype(D); flux_row=maximum(abs,D[end,:])
    defect=zero(T); scale=zero(T)
    for (k,v) in theta
        f=_sh_nf_to_orth_factor(k...,T); inner,outer,kind=bc[k]
        outer_defect=kind===:fixed_temperature ? v[end]-outer : (dot(D[end,:],v)-outer)/flux_row
        defect=max(defect,f*abs(v[1]-inner),f*abs(outer_defect))
        scale=max(scale,f*maximum(abs,v))
    end
    iszero(scale) ? defect : defect/scale
end

"""Largest change between the coefficient dictionaries of each `(a, b, weight)` triple,
relative to their largest weighted coefficient. Missing modes count as zero."""
function _relative_change(triples,::Type{T},N) where T
    change=zero(T); scale=zero(T)
    for (a,b,weight) in triples, k in union(keys(a),keys(b))
        va=get(a,k,zeros(T,N)); vb=get(b,k,zeros(T,N)); w=weight(k)
        change=max(change,w*maximum(abs,vb-va))
        scale=max(scale,w*maximum(abs,va),w*maximum(abs,vb))
    end
    iszero(scale) ? change : change/scale
end

"""Damped coupled Picard iteration, backtracking on the fixed-point residual.

One undamped Picard update solves heat transport at fixed velocity, then momentum
with that temperature and frozen inertia. Its relative change of the orthonormal
temperature coefficients and flow potentials measures convergence; unlike the
momentum collocation defect, it reaches round-off at any radial resolution."""
function _iterate_mean_state(theta,flow,D,D2,E,Ra,Pr,bc,mechanical_bc;
        momentum_model=:navier_stokes,max_iterations=50,tolerance=1e-8,
        relaxation=.5,verbose=false)
    T=eltype(flow.r); N=length(flow.r); systems=Dict{Int,Any}()
    inertial=momentum_model===:navier_stokes
    orthonormal=k->_sh_nf_to_orth_factor(k...,T); unit=_->one(T)
    function picard(temperature,velocity)
        inertia=inertial ? _mean_inertia(velocity,D) : nothing
        θ=_mean_temperature_step(velocity,D,D2,E/Pr,bc)
        u=_steady_mean_flow(θ,velocity.r,D,D2,E,Ra,Pr,velocity.lmax,velocity.mmax;
            mechanical_bc=mechanical_bc,inertia=inertia,systems=systems)
        heat=_relative_change(((temperature,θ,orthonormal),),T,N)
        mom=_relative_change(((velocity.p,u.p,unit),(velocity.t,u.t,unit)),T,N)
        _,mbc=_mean_momentum_residual(temperature,velocity,D,D2,E,Ra,Pr,mechanical_bc,inertia,systems)
        hbc=_mean_thermal_boundary_residual(temperature,D,bc)
        (theta=θ,flow=u,momentum=mom,thermal=heat,boundary=max(mbc,hbc),total=max(mom,heat,mbc,hbc))
    end
    image=picard(theta,flow)
    history=T[]; mhistory=T[]; thistory=T[]; steps=T[]
    reason=:max_iterations
    for iter in 1:max_iterations
        α=T(relaxation); accepted=false
        for backtrack in 0:10
            trial_theta=Dict(k=>(1-α).*v.+α.*image.theta[k] for (k,v) in theta)
            trial_flow=_blend_mean_flow(flow,image.flow,α,D,D2)
            trial=picard(trial_theta,trial_flow)
            if isfinite(trial.total) && (trial.total<=tolerance ||
                    trial.total < (1-T(1e-4)*α)*image.total)
                theta=trial_theta; flow=trial_flow; image=trial; accepted=true
                break
            end
            α/=2
        end
        push!(history,image.total); push!(mhistory,image.momentum)
        push!(thistory,image.thermal); push!(steps,accepted ? α : zero(T))
        verbose && println("  Iteration $iter: momentum=$(image.momentum), thermal=$(image.thermal), step=$(steps[end])")
        if image.total<=tolerance
            reason=:converged
            break
        elseif !accepted
            reason=:stagnation
            break
        end
    end
    info=(iterations=length(history),converged=reason===:converged,
        residual_history=history,thermal_residual=image.thermal,
        momentum_residual=image.momentum,boundary_residual=image.boundary,
        momentum_residual_history=mhistory,thermal_residual_history=thistory,
        step_history=steps,momentum_model=momentum_model,termination_reason=reason)
    theta,flow,info
end
