# Nonlinear steady momentum balance in the same solenoidal basis as the Stokes
# solve. -(U·∇)U = U×curl(U) - ∇(|U|²/2); the last term is absorbed in pressure.

"""Evaluate the physical vorticity of native mean-flow potentials."""
function _mean_vorticity_grid(flow::SolenoidalMeanFlow{T},i,g) where T
    R=Dict{Tuple{Int,Int},T}(); S=empty(R); V=empty(R); r=flow.r[i]
    for (key,p) in flow.p
        l,m=key; q=l*(l+1)
        R[key]=-q*flow.t[key][i]/r^2
        S[key]=-flow.dt[key][i]/r
        V[key]=(flow.d2p[key][i]-q*p[i]/r^2)/r
    end
    wr=sh_synthesize(R,g)
    wθ=sh_synthesize(S,g;Yf=_sh_dYθ)-sh_synthesize(V,g;Yf=_sh_dYφ_over_sin)
    wφ=sh_synthesize(S,g;Yf=_sh_dYφ_over_sin)+sh_synthesize(V,g;Yf=_sh_dYθ)
    wr,wθ,wφ
end

"""Project the pointwise cross product `a×b` of two solenoidal fields, `a(i, g)` and
`b(i, g)` giving the grid components at radial node `i`, onto every retained
harmonic: radial (R), spheroidal (S) and toroidal (V) coefficients, and the poloidal
row combination R - ∂r(rS), which also eliminates a pressure gradient."""
function _mean_cross_projection(a,b,r::Vector{T},D1,lmax,mmax) where T
    g=sh_grid(lmax,mmax,T); N=length(r)
    modes=[(l,m) for m in -g.mmax:g.mmax for l in max(1,abs(m)):g.lmax]
    R=Dict(k=>zeros(T,N) for k in modes)
    S=Dict(k=>zeros(T,N) for k in modes)
    V=Dict(k=>zeros(T,N) for k in modes)
    for i in 1:N
        ur,uθ,uφ=a(i,g)
        wr,wθ,wφ=b(i,g)
        fr=uθ.*wφ-uφ.*wθ
        fθ=uφ.*wr-ur.*wφ
        fφ=ur.*wθ-uθ.*wr
        radial=sh_analyze(fr,g)
        spheroidal=sh_horizontal_divergence(fθ,fφ,g)
        toroidal=sh_horizontal_divergence(fφ,-fθ,g)
        for k in modes
            q=k[1]*(k[1]+1)
            R[k][i]=radial[k]
            S[k][i]=-spheroidal[k]/q
            V[k][i]=-toroidal[k]/q
        end
    end
    # Angular products are dealiased by the oversampled SH grid; radial derivatives
    # use the collocation operator.
    p=Dict(k=>R[k]-D1*(r.*S[k]) for k in modes)
    (p=p,t=V,radial=R,spheroidal=S)
end

"""Project U×curl(U), including all retained harmonics generated by products."""
_mean_inertia(flow::SolenoidalMeanFlow,D1) =
    _mean_cross_projection((i,g)->_mean_flow_grid(flow,i,g),(i,g)->_mean_vorticity_grid(flow,i,g),
                           flow.r,D1,flow.lmax,flow.mmax)

"""Lorentz force of the induced field on itself, Le² J̄×b̄ = -Le² b̄×(∇×b̄)."""
function _mean_lorentz(field::SolenoidalMeanFlow,D1,Le2)
    f=_mean_cross_projection((i,g)->_mean_flow_grid(field,i,g),
        (i,g)->_mean_vorticity_grid(field,i,g),field.r,D1,field.lmax,field.mmax)
    scale(d)=Dict(k=>-Le2 .* v for (k,v) in d)
    (p=scale(f.p),t=scale(f.t),radial=scale(f.radial),spheroidal=scale(f.spheroidal))
end

"""EMF U×b̄ of the mean flow and the induced field."""
_mean_emf(flow::SolenoidalMeanFlow,field::SolenoidalMeanFlow,D1) =
    _mean_cross_projection((i,g)->_mean_flow_grid(flow,i,g),(i,g)->_mean_flow_grid(field,i,g),
                           flow.r,D1,flow.lmax,flow.mmax)

function _blend_mean_flow(a::SolenoidalMeanFlow{T},b::SolenoidalMeanFlow{T},α,D,D2) where T
    ks=union(keys(a.p),keys(b.p)); N=length(a.r)
    blend(da,db)=Dict(k=>(1-α).*get(da,k,zeros(T,N)) .+ α.*get(db,k,zeros(T,N)) for k in ks)
    p=blend(a.p,b.p); t=blend(a.t,b.t)
    SolenoidalMeanFlow(a.lmax,a.mmax,a.r,p,t,Dict(k=>D*v for (k,v) in p),
        Dict(k=>D2*v for (k,v) in p),Dict(k=>D*v for (k,v) in t))
end

"""Momentum collocation defect relative to the size of the equation's terms, and the
mechanical boundary/gauge defect of the row-scaled system relative to the largest
potential.

A diagnostic, not a convergence measure: through the viscous D⁴ rows even an exact
linear solve leaves a defect that grows roughly like N⁹."""
function _mean_momentum_residual(theta,flow,D,D2,E,Ra,Pr,mechanical_bc,inertia,systems;
        field=nothing,induction=nothing,magnetic=nothing)
    r=flow.r; T=eltype(r); N=length(r)
    θ=_sh_rescale(theta,+1); β=T(Ra*E^2/(Pr*(last(r)-first(r))^3))
    residual=zero(T); boundary=zero(T); terms=zero(T); xscale=zero(T)
    for am in 0:flow.mmax
        active=any(l>0 && abs(m)==am && any(!iszero,v) for ((l,m),v) in θ) ||
            any(abs(m)==am for (l,m) in keys(flow.p))
        if inertia!==nothing
            active |= any(abs(m)==am && any(!iszero,v) for d in (inertia.p,inertia.t) for ((l,m),v) in d)
        end
        active || continue
        system=get!(systems,am) do
            _mean_momentum_system(r,D,D2,E,flow.lmax,am,mechanical_bc;magnetic=magnetic)
        end
        f=_mean_momentum_rhs(system,θ,inertia,r,β;induction=induction)
        x=zeros(T,length(f)); n=length(system.modes)
        for (a,k) in enumerate(system.modes)
            rows=(a-1)*N+1:a*N
            x[rows]=get(flow.p,k,zeros(T,N)); x[n*N .+ rows]=get(flow.t,k,zeros(T,N))
            if field!==nothing
                x[2n*N .+ rows]=get(field.p,k,zeros(T,N)); x[3n*N .+ rows]=get(field.t,k,zeros(T,N))
            end
        end
        # A stress-free gauge multiplier is not a physical applied torque. Keep
        # it zero here so nonzero torque cannot be hidden in the residual.
        Ax=system.matrix*x; defect=Ax-f
        physical=system.physical; constraints=setdiff(eachindex(f),physical)
        residual=max(residual,maximum(abs,defect[physical]))
        terms=max(terms,maximum(abs,Ax[physical]),maximum(abs,f[physical]))
        boundary=max(boundary,maximum(abs,defect[constraints]./system.scales[constraints]))
        xscale=max(xscale,maximum(abs,x))
    end
    (iszero(terms) ? residual : residual/terms),(iszero(xscale) ? boundary : boundary/xscale)
end

"""Thermal boundary-condition defect relative to the largest orthonormal temperature
coefficient. Flux rows are divided by the largest derivative weight at the wall."""
function _mean_thermal_boundary_residual(theta,D,bc)
    T=eltype(D)
    defect=zero(T); scale=zero(T)
    wall_defect(v,row,kind,value)=kind===:fixed_temperature ? v[row]-value :
        (dot(D[row,:],v)-value)/maximum(abs,D[row,:])
    for (k,v) in theta
        f=_sh_nf_to_orth_factor(k...,T); inner,outer,kind=bc[k]
        inner_kind,outer_kind=_mean_bc_kinds(kind)
        defect=max(defect,f*abs(wall_defect(v,1,inner_kind,inner)),
                   f*abs(wall_defect(v,length(v),outer_kind,outer)))
        scale=max(scale,f*maximum(abs,v))
    end
    iszero(scale) ? defect : defect/scale
end

"""Largest change between the coefficient dictionaries of each `(a, b, weight)` triple,
relative to their largest weighted coefficient. Missing modes count as zero."""
function _relative_change(triples,::Type{T},N) where T
    change=zero(T); scale=zero(T)
    for (a,b,weight) in triples, k in union(keys(a),keys(b))
        va=get(a,k,zeros(T,N)); vb=get(b,k,zeros(T,N)); w=weight(k)
        change=max(change,w*maximum(abs,vb-va))
        scale=max(scale,w*maximum(abs,va),w*maximum(abs,vb))
    end
    iszero(scale) ? change : change/scale
end

"""Arnoldi–GMRES for the linear map `A`: the minimal-residual combination of at
most `maxiter` Krylov vectors, stopping once the residual is below `rtol*‖b‖`."""
function _gmres(A,b;rtol,maxiter=40)
    T=eltype(b); β=norm(b); iszero(β) && return zero(b)
    V=[b/β]; H=zeros(T,maxiter+1,maxiter); e1=zeros(T,maxiter+1); e1[1]=β
    for j in 1:maxiter
        w=A(V[j])
        for _ in 1:2, i in 1:j      # Gram–Schmidt, repeated once for orthogonality
            c=dot(V[i],w); H[i,j]+=c; w.-=c.*V[i]
        end
        H[j+1,j]=norm(w)
        y=H[1:j+1,1:j]\e1[1:j+1]
        if norm(H[1:j+1,1:j]*y-e1[1:j+1])<=rtol*β || H[j+1,j]<=eps(T)*β || j==maxiter
            return sum(y[i].*V[i] for i in 1:j)
        end
        push!(V,w./H[j+1,j])
    end
end

"""Inexact Newton–Krylov solve of the fixed point `Φ(x) = x`.

Each step solves `(Φ'(x) - I) d = x - Φ(x)` by GMRES with finite-difference
Jacobian products, then backtracks on the residual norm weighted by `weights(x)`,
which balances blocks of different magnitude. `record(x, Φx, λ)` is called after
every step, with `λ = 0` when the line search fails. Returns `(x, steps, done)`,
where `done` reports `converged(x, Φx)`."""
function _newton_krylov(Φ,x,weights,converged,record;max_steps,forcing=1e-3)
    T=eltype(x); Φx=Φ(x); steps=0
    while !converged(x,Φx)
        steps<max_steps || return x,steps,false
        steps+=1
        w=weights(x); F=Φx-x; wnorm(v)=norm(w.*v)
        jacobian(v̂)=let v=v̂./w, h=sqrt(eps(T))*max(wnorm(x),one(T))/max(wnorm(v),floatmin(T))
            w.*((Φ(x+h*v)-Φx)/h-v)
        end
        d=_gmres(jacobian,-(w.*F);rtol=forcing)./w
        λ=one(T)
        while true
            trial=x+λ*d; Φt=Φ(trial)
            if wnorm(Φt-trial)<(1-T(1e-4)*λ)*wnorm(F)
                x,Φx=trial,Φt; record(x,Φx,λ); break
            end
            λ/=2
            if λ<T(1/64)
                record(x,Φx,zero(T)); return x,steps,false
            end
        end
    end
    x,steps,true
end

"""Damped coupled Picard iteration, backtracking on the fixed-point residual, with a
Newton–Krylov fallback.

One undamped Picard update solves heat transport, then momentum with that
temperature and frozen inertia. The heat step advects temperature anomalies with
the previous velocity but the spherical mean temperature with the velocity the new
temperature drives, so the linear buoyancy feedback is solved exactly and only the
nonlinear transport is lagged. Its relative change of the orthonormal
temperature coefficients and flow potentials measures convergence; unlike the
momentum collocation defect, it reaches round-off at any radial resolution.
This only measures iteration convergence at the chosen truncation. The returned
`iteration_converged` aliases `converged`; `spatial_convergence=:unchecked`
requires the caller to compare independently refined states.

If the Picard iteration stalls, Newton–Krylov steps on the same fixed-point
equation continue from the stalled iterate. If they fail too, the boundary
anomalies (every boundary value except the spherical mean) are scaled by a
factor s, raised from 0, where conduction is exact, toward 1 by natural-parameter
continuation. `forcing_reached` is the largest s with a converged steady state;
below 1, the steady branch connected to weak forcing typically ends in a fold
there. Every Picard or Newton step counts toward `max_iterations`."""
function _iterate_mean_state(theta,flow,D,D2,E,Ra,Pr,bc,mechanical_bc;
        momentum_model=:navier_stokes,max_iterations=50,tolerance=1e-8,
        relaxation=.5,verbose=false,newton=true,magnetic=nothing,field=nothing)
    T=eltype(flow.r); N=length(flow.r); r=flow.r; systems=Dict{Int,Any}()
    inertial=momentum_model===:navier_stokes
    orthonormal=k->_sh_nf_to_orth_factor(k...,T); unit=_->one(T)
    β=T(Ra*E^2/(Pr*(last(r)-first(r))^3))
    mhd=magnetic!==nothing
    Le2=mhd ? T(magnetic.Le)^2 : zero(T)
    if mhd && field===nothing
        none=Dict{Tuple{Int,Int},Vector{T}}()
        field=SolenoidalMeanFlow(flow.lmax,flow.mmax,r,none,copy(none),copy(none),copy(none),copy(none))
    end
    responses=Dict(am=>begin
        system=get!(()->_mean_momentum_system(r,D,D2,E,flow.lmax,am,mechanical_bc;magnetic=magnetic),
                    systems,am)
        (modes=system.modes,G=_mean_buoyancy_response(system,r,β))
    end for am in 0:flow.mmax)
    # The flow driven by the frozen forcing alone and the spherical mean gradient
    # complete the implicit buoyancy feedback of the heat step.
    function feedback(temperature,forcing,induction)
        forced=Dict{Tuple{Int,Int},Vector{T}}()
        if forcing!==nothing || induction!==nothing
            for am in 0:flow.mmax
                system=systems[am]
                sol=_mean_momentum_solve(system,_mean_momentum_rhs(system,
                    Dict{Tuple{Int,Int},Vector{T}}(),forcing,r,β;induction=induction))
                for (a,key) in enumerate(system.modes)
                    forced[key]=sol[(a-1)*N+1:a*N]
                end
            end
        end
        (gradient=D*get(temperature,(0,0),zeros(T,N)),responses=responses,forced=forced)
    end
    # Frozen nonlinear forcing: inertia (unless momentum_model=:stokes) and, with an
    # induced field, its Lorentz force Le²J̄×b̄ on the flow and the EMF U×b̄.
    function nonlinear(velocity,b̄)
        forcing=inertial ? _mean_inertia(velocity,D) : nothing
        induction=nothing
        if mhd && any(any(!iszero,v) for d in (b̄.p,b̄.t) for v in values(d))
            lorentz=_mean_lorentz(b̄,D,Le2)
            forcing=forcing===nothing ? lorentz :
                (p=Dict(k=>forcing.p[k].+lorentz.p[k] for k in keys(lorentz.p)),
                 t=Dict(k=>forcing.t[k].+lorentz.t[k] for k in keys(lorentz.t)))
            induction=_mean_emf(velocity,b̄,D)
        end
        forcing,induction
    end
    function update(temperature,velocity,b̄,walls)
        forcing,induction=nonlinear(velocity,b̄)
        θ=_mean_temperature_step(velocity,D,D2,E/Pr,walls;
            feedback=feedback(temperature,forcing,induction))
        if mhd
            u,b=_steady_mean_mhd(θ,r,D,D2,E,Ra,Pr,velocity.lmax,velocity.mmax;magnetic=magnetic,
                mechanical_bc=mechanical_bc,forcing=forcing,induction=induction,systems=systems)
        else
            u=_steady_mean_flow(θ,r,D,D2,E,Ra,Pr,velocity.lmax,velocity.mmax;
                mechanical_bc=mechanical_bc,inertia=forcing,systems=systems)
            b=nothing
        end
        θ,u,b,forcing,induction
    end
    # The boundary/gauge defect does not involve the forcing, so `nothing` serves too.
    function measure(temperature,velocity,b̄,θ,u,b,forcing,induction,walls)
        heat=_relative_change(((temperature,θ,orthonormal),),T,N)
        mom=_relative_change(((velocity.p,u.p,unit),(velocity.t,u.t,unit)),T,N)
        mag=mhd ? _relative_change(((b̄.p,b.p,unit),(b̄.t,b.t,unit)),T,N) : zero(T)
        _,mbc=_mean_momentum_residual(temperature,velocity,D,D2,E,Ra,Pr,mechanical_bc,forcing,systems;
            field=b̄,induction=induction,magnetic=magnetic)
        hbc=_mean_thermal_boundary_residual(temperature,D,walls)
        (theta=θ,flow=u,field=b,momentum=mom,thermal=heat,induction=mag,
         boundary=max(mbc,hbc),total=max(mom,heat,mag,mbc,hbc))
    end
    picard(temperature,velocity,b̄,walls=bc)=
        measure(temperature,velocity,b̄,update(temperature,velocity,b̄,walls)...,walls)
    start=(theta,flow,field)
    image=picard(theta,flow,field)
    history=T[]; mhistory=T[]; thistory=T[]; steps=T[]
    reason=:max_iterations
    for iter in 1:max_iterations
        α=T(relaxation); accepted=false
        for backtrack in 0:10
            trial_theta=Dict(k=>(1-α).*v.+α.*image.theta[k] for (k,v) in theta)
            trial_flow=_blend_mean_flow(flow,image.flow,α,D,D2)
            trial_field=mhd ? _blend_mean_flow(field,image.field,α,D,D2) : nothing
            trial=picard(trial_theta,trial_flow,trial_field)
            if isfinite(trial.total) && (trial.total<=tolerance ||
                    trial.total < (1-T(1e-4)*α)*image.total)
                theta=trial_theta; flow=trial_flow; field=trial_field; image=trial; accepted=true
                break
            end
            α/=2
        end
        push!(history,image.total); push!(mhistory,image.momentum)
        push!(thistory,image.thermal); push!(steps,accepted ? α : zero(T))
        verbose && println("  Iteration $iter: momentum=$(image.momentum), thermal=$(image.thermal)" *
                           (mhd ? ", induction=$(image.induction)" : "") * ", step=$(steps[end])")
        if image.total<=tolerance
            reason=:converged
            break
        elseif !accepted
            reason=:stagnation
            break
        end
    end
    fhistory=fill(one(T),length(history)); newton_steps=0; forcing_reached=one(T)
    if newton && reason===:stagnation && length(history)<max_iterations
        # Flat coefficient vectors for the Newton–Krylov solve: orthonormal temperature
        # coefficients, then the poloidal and toroidal potentials of the flow and of
        # the induced field.
        L=flow.lmax; Mmax=flow.mmax
        tkeys=[(l,m) for m in -Mmax:Mmax for l in abs(m):L]
        fkeys=[(l,m) for m in -Mmax:Mmax for l in max(1,abs(m)):L]
        nt=length(tkeys)*N; nf=length(fkeys)*N
        zero_profile=zeros(T,N); get0(d,k)=get(d,k,zero_profile)
        function pack(θ,u,b)
            parts=[[get0(θ,k).*orthonormal(k) for k in tkeys];[get0(u.p,k) for k in fkeys];
                   [get0(u.t,k) for k in fkeys]]
            mhd && append!(parts,[[get0(b.p,k) for k in fkeys];[get0(b.t,k) for k in fkeys]])
            reduce(vcat,parts)
        end
        function potentials(x,offset)
            p=Dict(k=>x[offset+(a-1)*N+1:offset+a*N] for (a,k) in enumerate(fkeys))
            t=Dict(k=>x[offset+nf+(a-1)*N+1:offset+nf+a*N] for (a,k) in enumerate(fkeys))
            SolenoidalMeanFlow(L,Mmax,r,p,t,Dict(k=>D*v for (k,v) in p),
                Dict(k=>D2*v for (k,v) in p),Dict(k=>D*v for (k,v) in t))
        end
        unpack(x)=(Dict(k=>x[(a-1)*N+1:a*N]./orthonormal(k) for (a,k) in enumerate(tkeys)),
                   potentials(x,nt),mhd ? potentials(x,nt+2nf) : nothing)
        function weights(x)
            a=maximum(abs,view(x,1:nt))
            w=vcat(fill(inv(max(a,floatmin(T))),nt),
                   fill(inv(max(maximum(abs,view(x,nt+1:nt+2nf)),eps(T)*a,floatmin(T))),2nf))
            mhd && (w=vcat(w,fill(inv(max(maximum(abs,view(x,nt+2nf+1:length(x))),eps(T)*a,
                                          floatmin(T))),2nf)))
            w
        end
        # Boundary anomalies scaled by s; the spherical mean keeps its full values.
        walls(s)=Dict(k=>k==(0,0) ? w : (s*w[1],s*w[2],w[3]) for (k,w) in bc)
        function solve_at(s,x)
            ws=walls(s)
            Φ(y)=pack(update(unpack(y)...,ws)[1:3]...)
            converged(y,Φy)=measure(unpack(y)...,unpack(Φy)...,nothing,nothing,ws).total<=tolerance
            function record(y,Φy,λ)
                m=measure(unpack(y)...,unpack(Φy)...,nothing,nothing,ws)
                push!(history,m.total); push!(mhistory,m.momentum); push!(thistory,m.thermal)
                push!(steps,λ); push!(fhistory,s)
                verbose && println("  Newton step (forcing scale $s): momentum=$(m.momentum), " *
                                   "thermal=$(m.thermal), step=$λ")
            end
            y,k,found=_newton_krylov(Φ,x,weights,converged,record;
                max_steps=min(15,max_iterations-length(history)))
            newton_steps+=k
            y,found
        end
        x,ok=solve_at(one(T),pack(theta,flow,field))
        if !ok && length(history)<max_iterations
            # Zero anomaly forcing: the spherical conduction profile alone, no flow.
            x0=pack(start...); a00=findfirst(==((0,0)),tkeys)
            x00=zero(x0); x00[(a00-1)*N+1:a00*N]=x0[(a00-1)*N+1:a00*N]
            done_s=zero(T); done_x=x00; previous=nothing; Δs=T(1)/4
            while done_s<1 && Δs>=T(1e-3) && length(history)<max_iterations
                s=min(one(T),done_s+Δs)
                guess=previous===nothing ? x00+s*(x0-x00) :
                    done_x+(s-done_s)/(done_s-previous[1])*(done_x-previous[2])
                n0=newton_steps
                y,converged_s=solve_at(s,guess)
                if converged_s
                    previous=(done_s,done_x); done_s,done_x=s,y
                    newton_steps-n0<=4 && (Δs*=2)
                else
                    Δs/=4
                end
            end
            forcing_reached=done_s; x=done_x; ok=done_s==1
        end
        if ok
            theta,flow,field=unpack(x); image=picard(theta,flow,field)
            reason=:converged
        elseif length(history)>=max_iterations
            reason=:max_iterations
        end
    end
    info=(iterations=length(history),converged=reason===:converged,
        residual_history=history,thermal_residual=image.thermal,
        momentum_residual=image.momentum,boundary_residual=image.boundary,
        momentum_residual_history=mhistory,thermal_residual_history=thistory,
        step_history=steps,momentum_model=momentum_model,termination_reason=reason,
        iteration_converged=reason===:converged,spatial_convergence=:unchecked,
        newton_iterations=newton_steps,forcing_reached=forcing_reached,forcing_history=fhistory,
        induction_residual=image.induction)
    theta,flow,info,field
end
