# Nonlinear steady momentum balance in the same solenoidal basis as the Stokes
# solve. -(U·∇)U = U×curl(U) - ∇(|U|²/2); the last term is absorbed in pressure.

"""Evaluate the physical vorticity of native mean-flow potentials."""
function _mean_vorticity_grid(flow::SolenoidalMeanFlow{T},i,g) where T
    R=Dict{Tuple{Int,Int},T}(); S=empty(R); V=empty(R); r=flow.r[i]
    for (key,p) in flow.p
        l,m=key; q=l*(l+1)
        R[key]=-q*flow.t[key][i]/r^2
        S[key]=-flow.dt[key][i]/r
        V[key]=(flow.d2p[key][i]-q*p[i]/r^2)/r
    end
    wr=sh_synthesize(R,g)
    wθ=sh_synthesize(S,g;Yf=_sh_dYθ)-sh_synthesize(V,g;Yf=_sh_dYφ_over_sin)
    wφ=sh_synthesize(S,g;Yf=_sh_dYφ_over_sin)+sh_synthesize(V,g;Yf=_sh_dYθ)
    wr,wθ,wφ
end

"""Project U×curl(U), including all retained harmonics generated by products."""
function _mean_inertia(flow::SolenoidalMeanFlow{T},D1) where T
    g=sh_grid(flow.lmax,flow.mmax,T); N=length(flow.r)
    modes=[(l,m) for m in -g.mmax:g.mmax for l in max(1,abs(m)):g.lmax]
    R=Dict(k=>zeros(T,N) for k in modes)
    S=Dict(k=>zeros(T,N) for k in modes)
    V=Dict(k=>zeros(T,N) for k in modes)
    for i in 1:N
        ur,uθ,uφ=_mean_flow_grid(flow,i,g)
        wr,wθ,wφ=_mean_vorticity_grid(flow,i,g)
        fr=uθ.*wφ-uφ.*wθ
        fθ=uφ.*wr-ur.*wφ
        fφ=ur.*wθ-uθ.*wr
        radial=sh_analyze(fr,g)
        spheroidal=sh_horizontal_divergence(fθ,fφ,g)
        toroidal=sh_horizontal_divergence(fφ,-fθ,g)
        for k in modes
            q=k[1]*(k[1]+1)
            R[k][i]=radial[k]
            S[k][i]=-spheroidal[k]/q
            V[k][i]=-toroidal[k]/q
        end
    end
    # Eliminate the pressure by R - ∂r(r S). Angular products are dealiased by
    # the oversampled SH grid; radial derivatives use the collocation operator.
    p=Dict(k=>R[k]-D1*(flow.r.*S[k]) for k in modes)
    (p=p,t=V,radial=R,spheroidal=S)
end

function _blend_mean_flow(a::SolenoidalMeanFlow{T},b::SolenoidalMeanFlow{T},α,D,D2) where T
    ks=union(keys(a.p),keys(b.p)); N=length(a.r)
    blend(da,db)=Dict(k=>(1-α).*get(da,k,zeros(T,N)) .+ α.*get(db,k,zeros(T,N)) for k in ks)
    p=blend(a.p,b.p); t=blend(a.t,b.t)
    SolenoidalMeanFlow(a.lmax,a.mmax,a.r,p,t,Dict(k=>D*v for (k,v) in p),
        Dict(k=>D2*v for (k,v) in p),Dict(k=>D*v for (k,v) in t))
end

"""Residual of projected momentum equations and mechanical constraints."""
function _mean_momentum_residual(theta,flow,D,D2,E,Ra,Pr,mechanical_bc,inertia,systems)
    r=flow.r; T=eltype(r); N=length(r)
    θ=_sh_rescale(theta,+1); β=T(Ra*E^2/(Pr*(last(r)-first(r))^3))
    residual=zero(T); boundary=zero(T)
    for am in 0:flow.mmax
        active=any(l>0 && abs(m)==am && any(!iszero,v) for ((l,m),v) in θ) ||
            any(abs(m)==am for (l,m) in keys(flow.p))
        if inertia!==nothing
            active |= any(abs(m)==am && any(!iszero,v) for d in (inertia.p,inertia.t) for ((l,m),v) in d)
        end
        active || continue
        system=get!(systems,am) do
            _mean_momentum_system(r,D,D2,E,flow.lmax,am,mechanical_bc)
        end
        f=_mean_momentum_rhs(system,θ,inertia,r,β)
        x=zeros(T,length(f)); n=length(system.modes)
        for (a,k) in enumerate(system.modes)
            rows=(a-1)*N+1:a*N
            x[rows]=get(flow.p,k,zeros(T,N)); x[n*N .+ rows]=get(flow.t,k,zeros(T,N))
        end
        # A stress-free gauge multiplier is not a physical applied torque. Keep
        # it zero here so nonzero torque cannot be hidden in the residual.
        defect=system.matrix*x-f
        residual=max(residual,maximum(abs,defect[system.physical]))
        boundary=max(boundary,maximum(abs,defect[setdiff(eachindex(f),system.physical)]))
    end
    residual,boundary
end

function _mean_thermal_residual(theta,flow,D,D2,κ,bc)
    T=eltype(flow.r); r=flow.r
    dtheta=Dict(k=>D*v for (k,v) in theta)
    adv=_mean_flow_advection(theta,dtheta,flow)
    residual=zero(T); boundary=zero(T)
    for (k,v) in theta
        l,m=k; scale=_sh_nf_to_orth_factor(l,m,T)
        defect=κ.*(D2*v+2 .*dtheta[k]./r-l*(l+1).*v./r.^2)-adv[k]
        residual=max(residual,scale*maximum(abs,defect[2:end-1]))
        inner,outer,kind=bc[k]
        boundary=max(boundary,scale*abs(v[1]-inner),
            scale*abs((kind===:fixed_temperature ? v[end] : dtheta[k][end])-outer))
    end
    residual,boundary
end

"""Damped coupled Picard iteration with residual-based backtracking."""
function _iterate_mean_state(theta,flow,D,D2,E,Ra,Pr,bc,mechanical_bc;
        momentum_model=:navier_stokes,max_iterations=50,tolerance=1e-8,
        relaxation=.5,verbose=false)
    T=eltype(flow.r); systems=Dict{Int,Any}()
    inertial=momentum_model===:navier_stokes
    inertia=inertial ? _mean_inertia(flow,D) : nothing
    function residuals(temperature,velocity,forcing)
        mom,mbc=_mean_momentum_residual(temperature,velocity,D,D2,E,Ra,Pr,mechanical_bc,forcing,systems)
        heat,hbc=_mean_thermal_residual(temperature,velocity,D,D2,E/Pr,bc)
        (momentum=mom,thermal=heat,boundary=max(mbc,hbc),total=max(mom,heat,mbc,hbc))
    end
    residual=residuals(theta,flow,inertia)
    history=T[]; mhistory=T[]; thistory=T[]; steps=T[]
    reason=:max_iterations
    for iter in 1:max_iterations
        candidate_theta=_mean_temperature_step(flow,D,D2,E/Pr,bc)
        candidate_flow=_steady_mean_flow(candidate_theta,flow.r,D,D2,E,Ra,Pr,flow.lmax,flow.mmax;
            mechanical_bc=mechanical_bc,inertia=inertia,systems=systems)
        α=T(relaxation); accepted=false
        for backtrack in 0:10
            trial_theta=Dict(k=>(1-α).*v.+α.*candidate_theta[k] for (k,v) in theta)
            trial_flow=_blend_mean_flow(flow,candidate_flow,α,D,D2)
            trial_inertia=inertial ? _mean_inertia(trial_flow,D) : nothing
            trial_residual=residuals(trial_theta,trial_flow,trial_inertia)
            if isfinite(trial_residual.total) && (trial_residual.total<=tolerance ||
                    trial_residual.total < (1-T(1e-4)*α)*residual.total)
                theta=trial_theta; flow=trial_flow; inertia=trial_inertia
                residual=trial_residual; accepted=true
                break
            end
            α/=2
        end
        push!(history,residual.total); push!(mhistory,residual.momentum)
        push!(thistory,residual.thermal); push!(steps,accepted ? α : zero(T))
        verbose && println("  Iteration $iter: momentum=$(residual.momentum), thermal=$(residual.thermal), step=$(steps[end])")
        if residual.total<=tolerance
            reason=:converged
            break
        elseif !accepted
            reason=:stagnation
            break
        end
    end
    info=(iterations=length(history),converged=reason===:converged,
        residual_history=history,thermal_residual=residual.thermal,
        momentum_residual=residual.momentum,boundary_residual=residual.boundary,
        momentum_residual_history=mhistory,thermal_residual_history=thistory,
        step_history=steps,momentum_model=momentum_model,termination_reason=reason)
    theta,flow,info
end
